# os yang akan digunakan 
os:
  - linux
# bahasa yang akan digunakan 
languange: php

# distro
dist: trusty

php:
  - '7.4'  

# service yang digunakan
services:
  - docker

# grouping pekerjaan 
jobs: 
  include:
    # lakukan testing
    - stage: "Tests"
      name: "Unit Test PHP"
      script:
      # - travis_retry composer install --ignore-platform-reqs   
      - travis_retry composer self-update      
      - travis_retry composer install --prefer-source --no-interaction
      - cp .env.example .env
      - php artisan key:generate
      - vendor/bin/phpunit tests/Feature/ExampleTest.php
      # lakukan build docker nya & publish ke docker hub
    - stage: "Build Docker Image"
      name: "Build Images Docker"
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build -t E-Learning-project-winnowing .
      - docker images
      - docker tag E-Learning-project-winnowing $DOCKER_USERNAME/uas-sister-laravel
      - docker push $DOCKER_USERNAME/uas-sister-laravel
      